### ISSUE TITLE
Balance is not printed correctly

### ISSUE THREAD

**Issue by pmitchev** [amjuarez/bytecoin#36]
The balance in simplewallet is not printed correctly (command line):

Output in old simplewallet:     
```
balance: 2276.97920788, unlocked balance: 2276.97920788
```
Output in new simplewallet:
```
balance: 0.00000000, unlocked balance: 2276.97920788
```

**Comment by amjuarez** [comment]
We should have provided a more extensive explanation on this one. Actually, it's not a bug, but a usability fix that was required for Bytecoin Wallet. 

Previously, "balance" was a sum of pending balance and unlocked balance. As of version 1.0.3 this behavior was fixed so that balance corresponds to pending balance. Note that in GUI wallet all three balances are available.

We're going to rename this field to avoid further confusion. The patch is being processed at the moment.

**Comment by pmitchev** [comment]
Can you change the text? It is a lot confusing, because in the previews version it was 
balance = pending + unlocked
and it is a bit shocking to see your balance as 0 instead of XXXX after the update

**Comment by amjuarez** [comment]
Yes, it will be changed in the fix coming out today.

**Comment by amjuarez** [comment]
The text has been changed, the new version is already available. Thank you for your help!
