### ISSUE TITLE
the balance of the wallet is not displayed in the pool

### ISSUE THREAD

**Issue by fish34** [amjuarez/bytecoin#43]
Hello!
Im not sure to ask this question you or pool authors, but maybe u can help, the balance of the wallet is not displayed in the pool, does the wallet have json_rpc[getbalance] command? Or maybe its using another? In pool config there is getbalance option "rpcMethod": "getbalance"

**Comment by amjuarez** [comment]
Hello, 

Bytecoins wallet does have a “getbalance” rpc method. 

We are confident that issue is hidden in changes that we’ve made to getbalance method. Before 1.0.3 version getbalance returned 2 parameters: balance and unlocked_balance. 

In 1.0.3 we’ve renamed those parameters to locked_amount and available_balance. So you should  contact pool operator (developer) and tell him to change those parameters to the newer version. 

Please let us know if that solved your problem.
