### ISSUE TITLE
Why bytecoin chooses LGPL 3?

### ISSUE THREAD

**Issue by nurazhar** [amjuarez/bytecoin#81]
Most project I've seen are MIT license.

Is this one of the reason why it is less adopted than monero?

**Comment by SMH17** [comment]
The reason why Bytecoin is less adopted than Monero is because Monero is doing a better job to advertise its coin and because of its promotion at the launch. Many bitcointalk users (a popular forum about cryptocurrencies with many followers) have not well accepted the fact that when the coin has been advertised much Bytecoin was already mined.  Unfortunately Bytecoin developers now continue to not update blog websites, post news, talk, all the things that could spread Bytecoin popularity. 

About difference between MIT and LGPL, in a nutshell:
-LGPL: if you modify my code, you must distribute your modifications. You can include unmodified LGPL code in proprietary code under certain conditions.
-MIT: do what you want with my code excepted pretend that the code is yours

This mean that LGPL is more effective to protect Open Source philosophy even in derivative projects that are based on this source code.
